env:
  browser: true
  es2021: true
parserOptions:
  sourceType: module
extends:
  - '@nuxtjs'
  - '@nuxtjs/eslint-config-typescript'
rules:
  '@typescript-eslint/no-unused-vars': 'warn'
  'no-trailing-spaces': 'warn'
  'vue/multi-word-component-names': 'off'
  'vue/no-v-model-argument': 'off'
  'vue/no-v-for-template-key': 'off'
  comma-dangle:
    - error
    - only-multiline
