env:
  browser: true
  es2021: true
parserOptions:
  sourceType: module
extends:
  - '@nuxtjs'
  - '@nuxtjs/eslint-config-typescript'
rules:
  '@typescript-eslint/no-unused-vars': 'warn'
  comma-dangle:
    - error
    - only-multiline

